language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - pip install -e ".[dev]"
  - pip install coveralls pytest-cov

script:
  - pytest --cov=mmsbm --cov-report=xml tests/

after_success:
  - coveralls --service=travis-ci
