language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - pip install .

script:
  - python -m pytest tests/*

after_success:
  bash <(curl -s https://codecov.io/bash)
